# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.swift import Swift

class TestSwift(unittest.TestCase):
    """Swift unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Swift:
        """Test Swift
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Swift`
        """
        model = Swift()
        if include_optional:
            return Swift(
                account_number = '',
                account_holder_name = '',
                account_holder_address = '',
                bank_name = '',
                bank_address = '',
                swift_code = '',
                reference = '',
                type = 'Swift'
            )
        else:
            return Swift(
                account_number = '',
                account_holder_name = '',
                bank_name = '',
                swift_code = '',
                type = 'Swift',
        )
        """

    def testSwift(self):
        """Test Swift"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
