# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.balances import Balances

class TestBalances(unittest.TestCase):
    """Balances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Balances:
        """Test Balances
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Balances`
        """
        model = Balances()
        if include_optional:
            return Balances(
                balance = {
                    'key' : trivium_python_sdk.models.balance.Balance(
                        total_balance = 1.337, 
                        available_balance = 1.337, )
                    }
            )
        else:
            return Balances(
                balance = {
                    'key' : trivium_python_sdk.models.balance.Balance(
                        total_balance = 1.337, 
                        available_balance = 1.337, )
                    },
        )
        """

    def testBalances(self):
        """Test Balances"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
