# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.create_payments_account_request import CreatePaymentsAccountRequest

class TestCreatePaymentsAccountRequest(unittest.TestCase):
    """CreatePaymentsAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePaymentsAccountRequest:
        """Test CreatePaymentsAccountRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePaymentsAccountRequest`
        """
        model = CreatePaymentsAccountRequest()
        if include_optional:
            return CreatePaymentsAccountRequest(
                user_id = '',
                currency_code = '',
                desired_bank_country = ''
            )
        else:
            return CreatePaymentsAccountRequest(
                user_id = '',
                currency_code = '',
                desired_bank_country = '',
        )
        """

    def testCreatePaymentsAccountRequest(self):
        """Test CreatePaymentsAccountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
