# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.user_details import UserDetails

class TestUserDetails(unittest.TestCase):
    """UserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDetails:
        """Test UserDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDetails`
        """
        model = UserDetails()
        if include_optional:
            return UserDetails(
                tax_id = '',
                company_name = '',
                email = '',
                full_name = '',
                preferred_name = '',
                country_of_incorporation = '',
                type = 'CompanyDetails',
                identity_number = '',
                nationality = ''
            )
        else:
            return UserDetails(
                tax_id = '',
                company_name = '',
                email = '',
                full_name = '',
                preferred_name = '',
                country_of_incorporation = '',
                type = 'CompanyDetails',
                identity_number = '',
                nationality = '',
        )
        """

    def testUserDetails(self):
        """Test UserDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
