# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.api.payments_api import PaymentsApi


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_payments_account_accountid(self) -> None:
        """Test case for get_api_v1_payments_account_accountid

        """
        pass

    def test_get_api_v1_payments_account_user_userid(self) -> None:
        """Test case for get_api_v1_payments_account_user_userid

        """
        pass

    def test_get_api_v1_payments_balances_userid(self) -> None:
        """Test case for get_api_v1_payments_balances_userid

        """
        pass

    def test_post_api_v1_payments_account(self) -> None:
        """Test case for post_api_v1_payments_account

        """
        pass

    def test_post_api_v1_payments_payout(self) -> None:
        """Test case for post_api_v1_payments_payout

        """
        pass

    def test_post_api_v1_payments_payout_approve(self) -> None:
        """Test case for post_api_v1_payments_payout_approve

        """
        pass


if __name__ == '__main__':
    unittest.main()
