# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.pending_fixed_deposit import PendingFixedDeposit

class TestPendingFixedDeposit(unittest.TestCase):
    """PendingFixedDeposit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PendingFixedDeposit:
        """Test PendingFixedDeposit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PendingFixedDeposit`
        """
        model = PendingFixedDeposit()
        if include_optional:
            return PendingFixedDeposit(
                placement_id = '',
                currency_code = '',
                provider_details = trivium_python_sdk.models.provider_details.ProviderDetails(
                    provider = '', 
                    product_name = '', 
                    product_distinction = '', 
                    currency_code = '', 
                    returns = 1.337, ),
                term = '',
                deposit_instructions = trivium_python_sdk.models.deposit_instructions.DepositInstructions(
                    local = [
                        null
                        ], 
                    global = [
                        null
                        ], ),
                type = 'PendingFixedDeposit'
            )
        else:
            return PendingFixedDeposit(
                placement_id = '',
                currency_code = '',
                provider_details = trivium_python_sdk.models.provider_details.ProviderDetails(
                    provider = '', 
                    product_name = '', 
                    product_distinction = '', 
                    currency_code = '', 
                    returns = 1.337, ),
                term = '',
                deposit_instructions = trivium_python_sdk.models.deposit_instructions.DepositInstructions(
                    local = [
                        null
                        ], 
                    global = [
                        null
                        ], ),
                type = 'PendingFixedDeposit',
        )
        """

    def testPendingFixedDeposit(self):
        """Test PendingFixedDeposit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
