# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.processing_fixed_deposit import ProcessingFixedDeposit

class TestProcessingFixedDeposit(unittest.TestCase):
    """ProcessingFixedDeposit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessingFixedDeposit:
        """Test ProcessingFixedDeposit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessingFixedDeposit`
        """
        model = ProcessingFixedDeposit()
        if include_optional:
            return ProcessingFixedDeposit(
                placement_id = '',
                invested_quantity = 1.337,
                currency_code = '',
                provider_details = trivium_python_sdk.models.provider_details.ProviderDetails(
                    provider = '', 
                    product_name = '', 
                    product_distinction = '', 
                    currency_code = '', 
                    returns = 1.337, ),
                term = '',
                type = 'ProcessingFixedDeposit'
            )
        else:
            return ProcessingFixedDeposit(
                placement_id = '',
                invested_quantity = 1.337,
                currency_code = '',
                provider_details = trivium_python_sdk.models.provider_details.ProviderDetails(
                    provider = '', 
                    product_name = '', 
                    product_distinction = '', 
                    currency_code = '', 
                    returns = 1.337, ),
                term = '',
                type = 'ProcessingFixedDeposit',
        )
        """

    def testProcessingFixedDeposit(self):
        """Test ProcessingFixedDeposit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
