# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.payout_response import PayoutResponse

class TestPayoutResponse(unittest.TestCase):
    """PayoutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayoutResponse:
        """Test PayoutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayoutResponse`
        """
        model = PayoutResponse()
        if include_optional:
            return PayoutResponse(
                payout_intention_id = '',
                from_amount = 1.337,
                from_currency = '',
                to_amount = 1.337,
                to_currency = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PayoutResponse(
                payout_intention_id = '',
                from_amount = 1.337,
                from_currency = '',
                to_amount = 1.337,
                to_currency = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPayoutResponse(self):
        """Test PayoutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
