# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.transaction_status import TransactionStatus

class TestTransactionStatus(unittest.TestCase):
    """TransactionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionStatus(self):
        """Test TransactionStatus"""
        # inst = TransactionStatus()

if __name__ == '__main__':
    unittest.main()
