# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.cash_deposit import CashDeposit

class TestCashDeposit(unittest.TestCase):
    """CashDeposit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashDeposit:
        """Test CashDeposit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashDeposit`
        """
        model = CashDeposit()
        if include_optional:
            return CashDeposit(
                transaction_id = '',
                product_id = '',
                quantity = 1.337,
                currency_code = '',
                received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'PENDING',
                type = 'CashDeposit'
            )
        else:
            return CashDeposit(
                transaction_id = '',
                product_id = '',
                quantity = 1.337,
                currency_code = '',
                received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'PENDING',
                type = 'CashDeposit',
        )
        """

    def testCashDeposit(self):
        """Test CashDeposit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
