# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_user_userid(self) -> None:
        """Test case for get_api_v1_user_userid

        """
        pass

    def test_get_api_v1_user_userid_sign_embedded(self) -> None:
        """Test case for get_api_v1_user_userid_sign_embedded

        """
        pass

    def test_post_api_v1_user(self) -> None:
        """Test case for post_api_v1_user

        """
        pass

    def test_post_api_v1_user_events(self) -> None:
        """Test case for post_api_v1_user_events

        """
        pass

    def test_post_api_v1_user_userid_documents(self) -> None:
        """Test case for post_api_v1_user_userid_documents

        """
        pass


if __name__ == '__main__':
    unittest.main()
