# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.local_transfer import LocalTransfer

class TestLocalTransfer(unittest.TestCase):
    """LocalTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocalTransfer:
        """Test LocalTransfer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocalTransfer`
        """
        model = LocalTransfer()
        if include_optional:
            return LocalTransfer(
                account_number = '',
                recipient_name = '',
                bank = 'DBS',
                reference = '',
                type = 'Fast'
            )
        else:
            return LocalTransfer(
                account_number = '',
                recipient_name = '',
                bank = 'DBS',
                type = 'Fast',
        )
        """

    def testLocalTransfer(self):
        """Test LocalTransfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
