# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.quote_details import QuoteDetails

class TestQuoteDetails(unittest.TestCase):
    """QuoteDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteDetails:
        """Test QuoteDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteDetails`
        """
        model = QuoteDetails()
        if include_optional:
            return QuoteDetails(
                sell_currency = '',
                buy_currency = '',
                fixed_side = 'Buy',
                amount = 1.337,
                recipient_bank_country = '',
                charge_type = 'OURS'
            )
        else:
            return QuoteDetails(
                sell_currency = '',
                buy_currency = '',
                amount = 1.337,
                recipient_bank_country = '',
                charge_type = 'OURS',
        )
        """

    def testQuoteDetails(self):
        """Test QuoteDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
