# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.instrument_quote import InstrumentQuote

class TestInstrumentQuote(unittest.TestCase):
    """InstrumentQuote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstrumentQuote:
        """Test InstrumentQuote
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstrumentQuote`
        """
        model = InstrumentQuote()
        if include_optional:
            return InstrumentQuote(
                bid = 1.337,
                ask = 1.337,
                high = 1.337,
                low = 1.337
            )
        else:
            return InstrumentQuote(
                bid = 1.337,
                ask = 1.337,
                high = 1.337,
                low = 1.337,
        )
        """

    def testInstrumentQuote(self):
        """Test InstrumentQuote"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
