# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.api.trading_api import TradingApi


class TestTradingApi(unittest.TestCase):
    """TradingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TradingApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_trading_instrument_available_userid(self) -> None:
        """Test case for get_api_v1_trading_instrument_available_userid

        """
        pass

    def test_get_api_v1_trading_instrument_userid_symbol(self) -> None:
        """Test case for get_api_v1_trading_instrument_userid_symbol

        """
        pass

    def test_get_api_v1_trading_positions_userid(self) -> None:
        """Test case for get_api_v1_trading_positions_userid

        """
        pass

    def test_post_api_v1_trading_order_userid(self) -> None:
        """Test case for post_api_v1_trading_order_userid

        """
        pass


if __name__ == '__main__':
    unittest.main()
