# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.payment_outgoing import PaymentOutgoing

class TestPaymentOutgoing(unittest.TestCase):
    """PaymentOutgoing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentOutgoing:
        """Test PaymentOutgoing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentOutgoing`
        """
        model = PaymentOutgoing()
        if include_optional:
            return PaymentOutgoing(
                transaction_id = '',
                product_id = '',
                quantity = 1.337,
                currency_code = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'PENDING',
                type = 'PaymentOutgoing'
            )
        else:
            return PaymentOutgoing(
                transaction_id = '',
                product_id = '',
                quantity = 1.337,
                currency_code = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'PENDING',
                type = 'PaymentOutgoing',
        )
        """

    def testPaymentOutgoing(self):
        """Test PaymentOutgoing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
