# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.user_status import UserStatus

class TestUserStatus(unittest.TestCase):
    """UserStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserStatus(self):
        """Test UserStatus"""
        # inst = UserStatus()

if __name__ == '__main__':
    unittest.main()
