# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.api.managed_portfolios_api import ManagedPortfoliosApi


class TestManagedPortfoliosApi(unittest.TestCase):
    """ManagedPortfoliosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ManagedPortfoliosApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_portfolio_available_userid(self) -> None:
        """Test case for get_api_v1_portfolio_available_userid

        """
        pass

    def test_get_api_v1_portfolio_performance_investedportfolioid(self) -> None:
        """Test case for get_api_v1_portfolio_performance_investedportfolioid

        """
        pass

    def test_get_api_v1_portfolio_positions_userid(self) -> None:
        """Test case for get_api_v1_portfolio_positions_userid

        """
        pass

    def test_post_api_v1_portfolio_deposit(self) -> None:
        """Test case for post_api_v1_portfolio_deposit

        """
        pass

    def test_post_api_v1_portfolio_redemption(self) -> None:
        """Test case for post_api_v1_portfolio_redemption

        """
        pass


if __name__ == '__main__':
    unittest.main()
