# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.transfer_details import TransferDetails

class TestTransferDetails(unittest.TestCase):
    """TransferDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferDetails:
        """Test TransferDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferDetails`
        """
        model = TransferDetails()
        if include_optional:
            return TransferDetails(
                account_number = '',
                recipient_name = '',
                bank = 'DBS',
                reference = '',
                type = 'Fast',
                account_holder_name = '',
                account_holder_address = '',
                bank_name = '',
                bank_address = '',
                swift_code = ''
            )
        else:
            return TransferDetails(
                account_number = '',
                recipient_name = '',
                bank = 'DBS',
                type = 'Fast',
                account_holder_name = '',
                bank_name = '',
                swift_code = '',
        )
        """

    def testTransferDetails(self):
        """Test TransferDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
