# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.instrument_information import InstrumentInformation

class TestInstrumentInformation(unittest.TestCase):
    """InstrumentInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstrumentInformation:
        """Test InstrumentInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstrumentInformation`
        """
        model = InstrumentInformation()
        if include_optional:
            return InstrumentInformation(
                symbol = '',
                description = '',
                quote = trivium_python_sdk.models.instrument_quote.InstrumentQuote(
                    bid = 1.337, 
                    ask = 1.337, 
                    high = 1.337, 
                    low = 1.337, ),
                currency_code = ''
            )
        else:
            return InstrumentInformation(
                symbol = '',
                description = '',
                quote = trivium_python_sdk.models.instrument_quote.InstrumentQuote(
                    bid = 1.337, 
                    ask = 1.337, 
                    high = 1.337, 
                    low = 1.337, ),
                currency_code = '',
        )
        """

    def testInstrumentInformation(self):
        """Test InstrumentInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
