# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.routing_code_type import RoutingCodeType

class TestRoutingCodeType(unittest.TestCase):
    """RoutingCodeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoutingCodeType(self):
        """Test RoutingCodeType"""
        # inst = RoutingCodeType()

if __name__ == '__main__':
    unittest.main()
