# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.create_onboarding_document_request import CreateOnboardingDocumentRequest

class TestCreateOnboardingDocumentRequest(unittest.TestCase):
    """CreateOnboardingDocumentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOnboardingDocumentRequest:
        """Test CreateOnboardingDocumentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOnboardingDocumentRequest`
        """
        model = CreateOnboardingDocumentRequest()
        if include_optional:
            return CreateOnboardingDocumentRequest(
                document_type = 'OTHER',
                document_name = ''
            )
        else:
            return CreateOnboardingDocumentRequest(
                document_type = 'OTHER',
                document_name = '',
        )
        """

    def testCreateOnboardingDocumentRequest(self):
        """Test CreateOnboardingDocumentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
