# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.retrieve_document_signing_link_response import RetrieveDocumentSigningLinkResponse

class TestRetrieveDocumentSigningLinkResponse(unittest.TestCase):
    """RetrieveDocumentSigningLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveDocumentSigningLinkResponse:
        """Test RetrieveDocumentSigningLinkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveDocumentSigningLinkResponse`
        """
        model = RetrieveDocumentSigningLinkResponse()
        if include_optional:
            return RetrieveDocumentSigningLinkResponse(
                url = ''
            )
        else:
            return RetrieveDocumentSigningLinkResponse(
                url = '',
        )
        """

    def testRetrieveDocumentSigningLinkResponse(self):
        """Test RetrieveDocumentSigningLinkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
