# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.cash_inbound_callback_event import CashInboundCallbackEvent

class TestCashInboundCallbackEvent(unittest.TestCase):
    """CashInboundCallbackEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashInboundCallbackEvent:
        """Test CashInboundCallbackEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashInboundCallbackEvent`
        """
        model = CashInboundCallbackEvent()
        if include_optional:
            return CashInboundCallbackEvent(
                user_id = '',
                amount = 1.337,
                currency_code = '',
                type = 'RedemptionSettled'
            )
        else:
            return CashInboundCallbackEvent(
                user_id = '',
                amount = 1.337,
                currency_code = '',
                type = 'RedemptionSettled',
        )
        """

    def testCashInboundCallbackEvent(self):
        """Test CashInboundCallbackEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
