# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.payments_account import PaymentsAccount

class TestPaymentsAccount(unittest.TestCase):
    """PaymentsAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentsAccount:
        """Test PaymentsAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentsAccount`
        """
        model = PaymentsAccount()
        if include_optional:
            return PaymentsAccount(
                account_id = '',
                currency_code = '',
                status = 'ACTIVE',
                provider = trivium_python_sdk.models.provider_details.ProviderDetails(
                    provider = '', 
                    product_name = '', 
                    product_distinction = '', 
                    currency_code = '', 
                    returns = 1.337, ),
                deposit_instructions = trivium_python_sdk.models.deposit_instructions.DepositInstructions(
                    local = [
                        null
                        ], 
                    global = [
                        null
                        ], )
            )
        else:
            return PaymentsAccount(
                account_id = '',
                currency_code = '',
                status = 'ACTIVE',
                provider = trivium_python_sdk.models.provider_details.ProviderDetails(
                    provider = '', 
                    product_name = '', 
                    product_distinction = '', 
                    currency_code = '', 
                    returns = 1.337, ),
                deposit_instructions = trivium_python_sdk.models.deposit_instructions.DepositInstructions(
                    local = [
                        null
                        ], 
                    global = [
                        null
                        ], ),
        )
        """

    def testPaymentsAccount(self):
        """Test PaymentsAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
