# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.api.statement_api import StatementApi


class TestStatementApi(unittest.TestCase):
    """StatementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatementApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_statement_monthly_userid(self) -> None:
        """Test case for get_api_v1_statement_monthly_userid

        """
        pass


if __name__ == '__main__':
    unittest.main()
