# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.beneficiary_details import BeneficiaryDetails

class TestBeneficiaryDetails(unittest.TestCase):
    """BeneficiaryDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BeneficiaryDetails:
        """Test BeneficiaryDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BeneficiaryDetails`
        """
        model = BeneficiaryDetails()
        if include_optional:
            return BeneficiaryDetails(
                company_name = '',
                address = '',
                city = '',
                country = '',
                state = '',
                postal_code = '',
                type = 'CorporateBeneficiaryDetails',
                first_name = '',
                last_name = ''
            )
        else:
            return BeneficiaryDetails(
                company_name = '',
                address = '',
                city = '',
                country = '',
                type = 'CorporateBeneficiaryDetails',
                first_name = '',
                last_name = '',
        )
        """

    def testBeneficiaryDetails(self):
        """Test BeneficiaryDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
