# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.company_details import CompanyDetails

class TestCompanyDetails(unittest.TestCase):
    """CompanyDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompanyDetails:
        """Test CompanyDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompanyDetails`
        """
        model = CompanyDetails()
        if include_optional:
            return CompanyDetails(
                tax_id = '',
                company_name = '',
                email = '',
                full_name = '',
                preferred_name = '',
                country_of_incorporation = '',
                type = 'CompanyDetails'
            )
        else:
            return CompanyDetails(
                tax_id = '',
                company_name = '',
                email = '',
                full_name = '',
                preferred_name = '',
                country_of_incorporation = '',
                type = 'CompanyDetails',
        )
        """

    def testCompanyDetails(self):
        """Test CompanyDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
