# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.cash_callback_event import CashCallbackEvent

class TestCashCallbackEvent(unittest.TestCase):
    """CashCallbackEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashCallbackEvent:
        """Test CashCallbackEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashCallbackEvent`
        """
        model = CashCallbackEvent()
        if include_optional:
            return CashCallbackEvent(
                account_id = '',
                user_id = '',
                type = 'CashAccountActivated',
                transaction_id = ''
            )
        else:
            return CashCallbackEvent(
                account_id = '',
                user_id = '',
                type = 'CashAccountActivated',
                transaction_id = '',
        )
        """

    def testCashCallbackEvent(self):
        """Test CashCallbackEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
