# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.account_type import AccountType

class TestAccountType(unittest.TestCase):
    """AccountType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountType(self):
        """Test AccountType"""
        # inst = AccountType()

if __name__ == '__main__':
    unittest.main()
