# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.past_return import PastReturn

class TestPastReturn(unittest.TestCase):
    """PastReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PastReturn:
        """Test PastReturn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PastReturn`
        """
        model = PastReturn()
        if include_optional:
            return PastReturn(
                years = 56,
                returns = 1.337
            )
        else:
            return PastReturn(
                years = 56,
                returns = 1.337,
        )
        """

    def testPastReturn(self):
        """Test PastReturn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
