# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.api.cash_api import CashApi


class TestCashApi(unittest.TestCase):
    """CashApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CashApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_cash_account_accountid(self) -> None:
        """Test case for get_api_v1_cash_account_accountid

        """
        pass

    def test_get_api_v1_cash_account_user_userid(self) -> None:
        """Test case for get_api_v1_cash_account_user_userid

        """
        pass

    def test_get_api_v1_cash_balance_userid(self) -> None:
        """Test case for get_api_v1_cash_balance_userid

        """
        pass

    def test_get_api_v1_cash_rates(self) -> None:
        """Test case for get_api_v1_cash_rates

        """
        pass

    def test_get_api_v1_cash_transactions_accountid(self) -> None:
        """Test case for get_api_v1_cash_transactions_accountid

        """
        pass

    def test_get_api_v1_cash_transactions_redemption_info(self) -> None:
        """Test case for get_api_v1_cash_transactions_redemption_info

        """
        pass

    def test_post_api_v1_cash_account(self) -> None:
        """Test case for post_api_v1_cash_account

        """
        pass

    def test_post_api_v1_cash_events(self) -> None:
        """Test case for post_api_v1_cash_events

        """
        pass

    def test_post_api_v1_cash_request_deposit_accountid(self) -> None:
        """Test case for post_api_v1_cash_request_deposit_accountid

        """
        pass

    def test_post_api_v1_cash_request_redemption_accountid(self) -> None:
        """Test case for post_api_v1_cash_request_redemption_accountid

        """
        pass

    def test_put_api_v1_cash_callback(self) -> None:
        """Test case for put_api_v1_cash_callback

        """
        pass


if __name__ == '__main__':
    unittest.main()
