# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.api.fixed_deposit_api import FixedDepositApi


class TestFixedDepositApi(unittest.TestCase):
    """FixedDepositApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FixedDepositApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_fixeddeposit_placement_placementid(self) -> None:
        """Test case for get_api_v1_fixeddeposit_placement_placementid

        """
        pass

    def test_get_api_v1_fixeddeposit_user_userid(self) -> None:
        """Test case for get_api_v1_fixeddeposit_user_userid

        """
        pass

    def test_put_api_v1_fixeddeposit_placement_placementid(self) -> None:
        """Test case for put_api_v1_fixeddeposit_placement_placementid

        """
        pass


if __name__ == '__main__':
    unittest.main()
