# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trivium_python_sdk.models.process_fixed_deposit_placement_request import ProcessFixedDepositPlacementRequest

class TestProcessFixedDepositPlacementRequest(unittest.TestCase):
    """ProcessFixedDepositPlacementRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessFixedDepositPlacementRequest:
        """Test ProcessFixedDepositPlacementRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessFixedDepositPlacementRequest`
        """
        model = ProcessFixedDepositPlacementRequest()
        if include_optional:
            return ProcessFixedDepositPlacementRequest(
                quantity = 1.337,
                transfer = trivium_python_sdk.models.transfer.Transfer(
                    from = null, 
                    to = null, )
            )
        else:
            return ProcessFixedDepositPlacementRequest(
                quantity = 1.337,
                transfer = trivium_python_sdk.models.transfer.Transfer(
                    from = null, 
                    to = null, ),
        )
        """

    def testProcessFixedDepositPlacementRequest(self):
        """Test ProcessFixedDepositPlacementRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
