# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from trivium_python_sdk.models.bank_account_details import BankAccountDetails
from trivium_python_sdk.models.beneficiary_details import BeneficiaryDetails
from trivium_python_sdk.models.quote_details import QuoteDetails
from typing import Optional, Set
from typing_extensions import Self

class AdHocPayoutIntention(BaseModel):
    """
    AdHocPayoutIntention
    """ # noqa: E501
    from_account_id: StrictStr = Field(alias="fromAccountId")
    quote: QuoteDetails
    beneficiary: BeneficiaryDetails
    bank_account_details: BankAccountDetails = Field(alias="bankAccountDetails")
    type: StrictStr
    __properties: ClassVar[List[str]] = ["fromAccountId", "quote", "beneficiary", "bankAccountDetails", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['AdHocPayoutIntention']):
            raise ValueError("must be one of enum values ('AdHocPayoutIntention')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdHocPayoutIntention from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of quote
        if self.quote:
            _dict['quote'] = self.quote.to_dict()
        # override the default output from pydantic by calling `to_dict()` of beneficiary
        if self.beneficiary:
            _dict['beneficiary'] = self.beneficiary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bank_account_details
        if self.bank_account_details:
            _dict['bankAccountDetails'] = self.bank_account_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdHocPayoutIntention from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fromAccountId": obj.get("fromAccountId"),
            "quote": QuoteDetails.from_dict(obj["quote"]) if obj.get("quote") is not None else None,
            "beneficiary": BeneficiaryDetails.from_dict(obj["beneficiary"]) if obj.get("beneficiary") is not None else None,
            "bankAccountDetails": BankAccountDetails.from_dict(obj["bankAccountDetails"]) if obj.get("bankAccountDetails") is not None else None,
            "type": obj.get("type")
        })
        return _obj


