# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AssetClass(str, Enum):
    """
    AssetClass
    """

    """
    allowed enum values
    """
    BONDS = 'BONDS'
    COMMODITY = 'COMMODITY'
    EQUITY = 'EQUITY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AssetClass from a JSON string"""
        return cls(json.loads(json_str))


