# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from trivium_python_sdk.models.international_transfer import InternationalTransfer
from trivium_python_sdk.models.local_transfer import LocalTransfer
from typing import Optional, Set
from typing_extensions import Self

class DepositInstructions(BaseModel):
    """
    DepositInstructions
    """ # noqa: E501
    local: Optional[List[LocalTransfer]] = None
    var_global: Optional[List[InternationalTransfer]] = Field(default=None, alias="global")
    __properties: ClassVar[List[str]] = ["local", "global"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DepositInstructions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in local (list)
        _items = []
        if self.local:
            for _item_local in self.local:
                if _item_local:
                    _items.append(_item_local.to_dict())
            _dict['local'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in var_global (list)
        _items = []
        if self.var_global:
            for _item_var_global in self.var_global:
                if _item_var_global:
                    _items.append(_item_var_global.to_dict())
            _dict['global'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DepositInstructions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "local": [LocalTransfer.from_dict(_item) for _item in obj["local"]] if obj.get("local") is not None else None,
            "global": [InternationalTransfer.from_dict(_item) for _item in obj["global"]] if obj.get("global") is not None else None
        })
        return _obj


