# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FastParticipant(str, Enum):
    """
    Full names of banks: DBS - DBS Bank Ltd, HSBC_CORP - HSBC Bank (Corporate), HSBC_SG - HSBC Bank (Singapore), ANEXT - Anext Bank Pte Ltd, ANZ - ANZ Bank, BANK_OF_CHINA - Bank of China, BNP - BNP Paribas, CIMB - CIMB Bank, CITI_NA - Citibank N.A., Singapore Branch, CITI_SG - Citibank Singapore Limited, DEUTSCHE - Deutsche Bank, GLDB - Green Link Digital Bank Pte Ltd, GXS - GXS Bank Pte Ltd, HL - Hong Leong Bank Singapore, ICICI - ICICI Bank Limited Singapore, ICBOC - Industrial and Commercial Bank of China Limited, JP_MORGAN - JPMorgan Chase Bank, N.A., MARIBANK - MariBank Singapore Private Limited, MAYBANK - Maybank Singapore Limited, MALAYAN_BANKING - Malayan Banking Berhad, MIZUHO - Mizuho Bank, MUFG - MUFG Bank, Ltd, OCBC - OCBC Bank, RHB - RHB Bank, STANDARD_CHARTERED - Standard Chartered Bank (Singapore) Limited, SING_FINANCE - Sing Investments & Finance Limited, SBI - State Bank of India, SMBC - Sumitomo Mitsui Banking Corporation, TRUST - Trust Bank Singapore Limited, UOB - United Overseas Bank  Full names of NFIs: GRAB_PAY - GPay Network (S) Pte Ltd, LIQUID - Liquid Group Pte Ltd, MATCHMOVE - MatchMove Pay Pte Ltd, NIUM - NIUM Pte Ltd, DASH - SingCash Pte Ltd, WISE - Wise Asia-Pacific Pte. Ltd., XFERS - Xfers Pte Ltd 
    """

    """
    allowed enum values
    """
    ANEXT = 'ANEXT'
    ANZ = 'ANZ'
    BANK_OF_CHINA = 'BANK_OF_CHINA'
    BNP = 'BNP'
    CIMB = 'CIMB'
    CITI_NA = 'CITI_NA'
    CITI_SG = 'CITI_SG'
    DASH = 'DASH'
    DBS = 'DBS'
    DEUTSCHE = 'DEUTSCHE'
    GLDB = 'GLDB'
    GRAB_PAY = 'GRAB_PAY'
    GXS = 'GXS'
    HL = 'HL'
    HSBC_CORP = 'HSBC_CORP'
    HSBC_SG = 'HSBC_SG'
    ICBOC = 'ICBOC'
    ICICI = 'ICICI'
    JP_MORGAN = 'JP_MORGAN'
    LIQUID = 'LIQUID'
    MALAYAN_BANKING = 'MALAYAN_BANKING'
    MARIBANK = 'MARIBANK'
    MATCHMOVE = 'MATCHMOVE'
    MAYBANK = 'MAYBANK'
    MIZUHO = 'MIZUHO'
    MUFG = 'MUFG'
    NIUM = 'NIUM'
    OCBC = 'OCBC'
    RHB = 'RHB'
    SBI = 'SBI'
    SING_FINANCE = 'SING_FINANCE'
    SMBC = 'SMBC'
    STANDARD_CHARTERED = 'STANDARD_CHARTERED'
    TRUST = 'TRUST'
    UOB = 'UOB'
    WISE = 'WISE'
    XFERS = 'XFERS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FastParticipant from a JSON string"""
        return cls(json.loads(json_str))


