# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FastParticipant(str, Enum):
    """
    Full names of banks: DBS - DBS Bank Ltd, HSBC_CORP - HSBC Bank (Corporate), HSBC_SG - HSBC Bank (Singapore) 
    """

    """
    allowed enum values
    """
    DBS = 'DBS'
    HSBC_CORP = 'HSBC_CORP'
    HSBC_SG = 'HSBC_SG'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FastParticipant from a JSON string"""
        return cls(json.loads(json_str))


