# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentPurpose(str, Enum):
    """
    GDDS - Payment for goods, SCVE - Payment for services, PAYR - Employee payroll, CASH - Capital transfer, INVS - Investment, CHAR - Charity donation, INTC - Transfer to own account, LOAR - Repayment of loan, OTHR - Others
    """

    """
    allowed enum values
    """
    CASH = 'CASH'
    CHAR = 'CHAR'
    GDDS = 'GDDS'
    INTC = 'INTC'
    INVS = 'INVS'
    LOAR = 'LOAR'
    OTHR = 'OTHR'
    PAYR = 'PAYR'
    SCVE = 'SCVE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentPurpose from a JSON string"""
        return cls(json.loads(json_str))


