# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class PayoutResponse(BaseModel):
    """
    PayoutResponse
    """ # noqa: E501
    payout_intention_id: StrictStr = Field(alias="payoutIntentionId")
    from_amount: Union[StrictFloat, StrictInt] = Field(alias="fromAmount")
    from_currency: StrictStr = Field(alias="fromCurrency")
    to_amount: Union[StrictFloat, StrictInt] = Field(alias="toAmount")
    to_currency: StrictStr = Field(alias="toCurrency")
    expires_at: datetime = Field(alias="expiresAt")
    __properties: ClassVar[List[str]] = ["payoutIntentionId", "fromAmount", "fromCurrency", "toAmount", "toCurrency", "expiresAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PayoutResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PayoutResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payoutIntentionId": obj.get("payoutIntentionId"),
            "fromAmount": obj.get("fromAmount"),
            "fromCurrency": obj.get("fromCurrency"),
            "toAmount": obj.get("toAmount"),
            "toCurrency": obj.get("toCurrency"),
            "expiresAt": obj.get("expiresAt")
        })
        return _obj


