# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from trivium_python_sdk.models.buy_sell import BuySell
from trivium_python_sdk.models.charge_type import ChargeType
from typing import Optional, Set
from typing_extensions import Self

class QuoteDetails(BaseModel):
    """
    QuoteDetails
    """ # noqa: E501
    sell_currency: StrictStr = Field(alias="sellCurrency")
    buy_currency: StrictStr = Field(alias="buyCurrency")
    fixed_side: Optional[BuySell] = Field(default=None, alias="fixedSide")
    amount: Union[StrictFloat, StrictInt]
    recipient_bank_country: StrictStr = Field(alias="recipientBankCountry")
    charge_type: ChargeType = Field(alias="chargeType")
    __properties: ClassVar[List[str]] = ["sellCurrency", "buyCurrency", "fixedSide", "amount", "recipientBankCountry", "chargeType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuoteDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuoteDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sellCurrency": obj.get("sellCurrency"),
            "buyCurrency": obj.get("buyCurrency"),
            "fixedSide": obj.get("fixedSide"),
            "amount": obj.get("amount"),
            "recipientBankCountry": obj.get("recipientBankCountry"),
            "chargeType": obj.get("chargeType")
        })
        return _obj


