# coding: utf-8

"""
    trivium-cash

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.8.dev4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RoutingCodeType(str, Enum):
    """
    RoutingCodeType
    """

    """
    allowed enum values
    """
    ABA = 'ABA'
    ACH_ROUTING_NUMBER = 'ACH_ROUTING_NUMBER'
    BANK_CODE = 'BANK_CODE'
    BIC_SWIFT = 'BIC_SWIFT'
    BRANCH_CODE = 'BRANCH_CODE'
    BSB_CODE = 'BSB_CODE'
    IFSC = 'IFSC'
    SORT_CODE = 'SORT_CODE'
    WIRE_ROUTING_NUMBER = 'WIRE_ROUTING_NUMBER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RoutingCodeType from a JSON string"""
        return cls(json.loads(json_str))


